namespace LibDuelistsOfTheRoses
{
    public enum CardType
    {
        Aqua,
        Beast,
        BeastWarrior,
        Dinosaur,
        DivineBeast,
        Dragon,
        Fairy,
        Fiend,
        Fish,
        Insect,
        Machine,
        Plant,
        PowerUp,
        Pyro,
        Reptile,
        Rock,
        SeaSerpent,
        Spellcaster,
        Thunder,
        Warrior,
        WingedBeast,
        Zombie,
        Spell,
        Ritual,
        Trap,
        Immortal
    }
}